### ISSUE TITLE
Stuck after authentication success and 500 err

### ISSUE THREAD

**Issue by quick2063706271** [EGA-archive/ega-download-client#237] opened 2024-08-12 17:44 UTC
**Stuck after authentication success**

**Description of the bug**

Hi, I tried to download file with `pyega3 -cf credential_file.json fetch EGAF00002863117`
What I get is 
```
[2024-08-12 13:34:57 -0400]
[2024-08-12 13:34:57 -0400] pyEGA3 - EGA python client version 5.2.0 (https://github.com/EGA-archive/ega-download-client)
[2024-08-12 13:34:57 -0400] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2024-08-12 13:34:57 -0400] Python version : 3.12.4
[2024-08-12 13:34:57 -0400] OS version : Darwin Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
[2024-08-12 13:34:57 -0400] MacOS version : 14.1
[2024-08-12 13:34:57 -0400] Server URL: https://ega.ebi.ac.uk:8443/v2
[2024-08-12 13:34:57 -0400] Session-Id: 2426883116
[2024-08-12 13:34:59 -0400]
[2024-08-12 13:34:59 -0400] Authentication success for user '<userid>'
urllib3.exceptions.ResponseError: too many 500 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 934, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /v2/metadata/files/EGAF00002863117 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<userid>/anaconda3/envs/pyega3/bin/pyega3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/pyega3/pyega3.py", line 153, in main
    execute_subcommand(args, data_client)
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/pyega3/libs/commands.py", line 22, in execute_subcommand
    fetch_data(args, data_client)
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/pyega3/libs/commands.py", line 49, in fetch_data
    file.download_file_retry(num_connections=args.connections,
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 286, in download_file_retry
    if self.name.endswith(".gpg"):
       ^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 90, in name
    self.load_metadata()
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 56, in load_metadata
    res = self.data_client.get_json(f"/files/{self.id}")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/pyega3/libs/data_client.py", line 61, in get_json
    r = self.session.get(url, headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<userid>/anaconda3/envs/pyega3/lib/python3.12/site-packages/requests/adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='ega.ebi.ac.uk', port=8443): Max retries exceeded with url: /v2/metadata/files/EGAF00002863117 (Caused by ResponseError('too many 500 error responses'))
```
Could you perhaps take a look at it?

**Comment by CsabaHalmagyi** [comment] 2024-08-12 20:34
Hello,
Thank you for submitting this. After carefully inspecting our logs, I can confirm that this issue is happening because the client is configured to use too many connections. 
Please try downloading the file with -c 1 (or not more than 5). 
Should you have any further issues downloading the file, please contact our helpdesk team directly, they can help with alternative ways of accessing the dataset.
Closing this issue, as this is not for the attention of the development team.

**Closed by CsabaHalmagyi** 2024-08-12 20:34 UTC
Labels: bug

**Comment by JMencius** [comment] 2025-11-20 17:14
@CsabaHalmagyi  
Hello, I think the `-c 1` still does not work:

```
(ega) mencius@exia:/TT16000NM00J/methqc/data$ pyega3 -d -cf key.json -c 1 fetch EGAD50000000573 --output-dir ./
[2025-11-21 01:12:42 +0800] 
[2025-11-21 01:12:42 +0800] pyEGA3 - EGA python client version 5.2.0 (https://github.com/EGA-archive/ega-download-client)
[2025-11-21 01:12:42 +0800] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2025-11-21 01:12:42 +0800] Python version : 3.7.12
[2025-11-21 01:12:42 +0800] OS version : Linux #220-Ubuntu SMP Fri Sep 27 13:19:16 UTC 2024
[2025-11-21 01:12:42 +0800] Server URL: https://ega.ebi.ac.uk:8443/v2
[2025-11-21 01:12:42 +0800] Session-Id: 3658954617
[2025-11-21 01:12:42 +0800] Starting new HTTPS connection (1): ipinfo.io:443
[2025-11-21 01:12:43 +0800] https://ipinfo.io:443 "GET /json HTTP/1.1" 200 None
[2025-11-21 01:12:43 +0800] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2025-11-21 01:12:45 +0800] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 200 None
[2025-11-21 01:12:45 +0800] 
[2025-11-21 01:12:45 +0800] Authentication success for user '${MY_EMAIL}'
[2025-11-21 01:12:45 +0800] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2025-11-21 01:12:46 +0800] https://ega.ebi.ac.uk:8443 "GET /v2/metadata/datasets HTTP/1.1" 500 None
[2025-11-21 01:12:46 +0800] Incremented Retry for (url='/v2/metadata/datasets'): Retry(total=19, connect=False, read=10, redirect=None, status=9)
[2025-11-21 01:12:46 +0800] Retry: /v2/metadata/datasets
[2025-11-21 01:12:46 +0800] https://ega.ebi.ac.uk:8443 "GET /v2/metadata/datasets HTTP/1.1" 500 None
[2025-11-21 01:12:46 +0800] Incremented Retry for (url='/v2/metadata/datasets'): Retry(total=18, connect=False, read=10, redirect=None, status=8)
[2025-11-21 01:12:47 +0800] Retry: /v2/metadata/datasets
[2025-11-21 01:12:48 +0800] https://ega.ebi.ac.uk:8443 "GET /v2/metadata/datasets HTTP/1.1" 500 None
[2025-11-21 01:12:48 +0800] Incremented Retry for (url='/v2/metadata/datasets'): Retry(total=17, connect=False, read=10, redirect=None, status=7)
[2025-11-21 01:12:50 +0800] Retry: /v2/metadata/datasets
[2025-11-21 01:12:50 +0800] https://ega.ebi.ac.uk:8443 "GET /v2/metadata/datasets HTTP/1.1" 500 None
[2025-11-21 01:12:50 +0800] Incremented Retry for (url='/v2/metadata/datasets'): Retry(total=16, connect=False, read=10, redirect=None, status=6)
[2025-11-21 01:12:55 +0800] Retry: /v2/metadata/datasets
[2025-11-21 01:12:55 +0800] https://ega.ebi.ac.uk:8443 "GET /v2/metadata/datasets HTTP/1.1" 500 None
[2025-11-21 01:12:55 +0800] Incremented Retry for (url='/v2/metadata/datasets'): Retry(total=15, connect=False, read=10, redirect=None, status=5)
[2025-11-21 01:13:05 +0800] Retry: /v2/metadata/datasets
```
