### ISSUE TITLE
IncompleteRead(68345518 bytes read, 1005396306 more expected))

### ISSUE THREAD

**Issue by Jungal10** [EGA-archive/ega-download-client#227] opened 2024-06-25 15:23 UTC
**Incomplete reads**

```
Traceback (most recent call last):
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 346, in _download_whole_file
    self.download_file(output_file, num_connections, max_slice_size)
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 162, in download_file
    for part_file_name in executor.map(self.download_file_slice_, params):
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 196, in download_file_slice_
    return self.download_file_slice(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/site-packages/pyega3/libs/data_file.py", line 231, in download_file_slice
    for chunk in r.iter_content(DOWNLOAD_FILE_MEMORY_BUFFER_SIZE):
  File "/home/JGoncalve/.conda/envs/ega/lib/python3.12/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(68345518 bytes read, 1005396306 more expected)', IncompleteRead(68345518 bytes read, 1005396306 more expected))

```

**Additional context**

I have been trying to download a dataset for weeks now. I tried the github version before, that lead to always getting md5sum that were not correct for ALL samples.
Now, I am using pyega3 via conda with the following version:
```
pyega3
[2024-06-25 14:03:33 +0200]
[2024-06-25 14:03:33 +0200] pyEGA3 - EGA python client version 5.2.0 (https://github.com/EGA-archive/ega-download-client)
[2024-06-25 14:03:33 +0200] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2024-06-25 14:03:33 +0200] Python version : 3.12.4
[2024-06-25 14:03:33 +0200] OS version : Linux #1 SMP PREEMPT_DYNAMIC Tue May 7 10:46:15 UTC 2024

```

I have made attempts with multiple settings, the latest one trying to reduce the slice sizes, but I continue not to have sucess.
What else can I do?

`pyega3  -ms 1073741824 -cf /home/storage/DataLake/Resources/tools/ega-download-client/CREDENTIALS_FILE.json -c 20 fetch EGAF00005776080 `

**Comment by CsabaHalmagyi** [comment] 2024-06-26 12:22
Hi @Jungal10 
Thank you for submitting the issue. I can confirm that the EGA file distribution API has been under very heavy pressure recently and this causes the incomplete read errors that lead to failed md5 checks (users create many requests and our API can't handle all requests in a timely manner). We are working on a server side solution, however if you need to download files in the meantime, I suggest contacting EGA Helpdesk directly at [helpdesk@ega-archive.org](mailto:helpdesk@ega-archive.org) . They should be able to provide you with alternative ways of downloading the datasets. 
I am closing this issue, as the problem is not related to the pyega3 client.

**Closed by CsabaHalmagyi** 2024-06-26 12:22 UTC
Labels: bug
