### ISSUE TITLE
Cannot Download authorized dataset

### ISSUE THREAD

**Issue by farhan-lab** [EGA-archive/ega-download-client#213] opened 2023-10-27 14:30 UTC
Dear EGA team,

My request for the data access to the dataset (EGA00001000745) was approved by the data access committee. Now that I would download the authorized data it gives an error message:

Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/home/sahmad/miniconda3/lib/python3.11/site-packages/pyega3/libs/auth_client.py", line 37, in token
    r.raise_for_status()
  File "/home/sahmad/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token

Could you please help to resolve this issue?
Thank you,
Best regards,
Farhan

**Comment by CsabaHalmagyi** [comment] 2023-10-27 14:42
Dear @farhan-lab,
Thank you for contacting EGA.  It seems that you did not authenticate successfully, therefore the API is refusing the download . Please check the username and password you use for authentication. If you forgot your password, you can request a reset here: https://ega-archive.org/forgot-password/
Should you encounter any problems, please contact our helpdesk team at helpdesk@ega-archive.org

Since this is not a bug, I am closing this issue. 
Regards,
Csaba

**Closed by CsabaHalmagyi** 2023-10-27 14:42 UTC

**Comment by farhan-lab** [comment] 2023-10-30 14:23
Dear Csab,

Thank you for your response. I have contacted helpdesk team at [helpdesk@ega-archive.org](mailto:helpdesk@ega-archive.org) but I get a response of "This ticket has been untaken by ega-rt-support." 

I can login EGA with my username and password but still cannot download the dataset for which I have been granted access by DAC.
Could you please guide me how can I request help from EGA ?

Best,
Farhan

**Comment by baishengjun** [comment] 2024-07-19 17:19
Hi, same issue with you
The EGA has emailed me that my request have beed approved, but I still can not access the autheried data.
Does you have solved this issue? Could you please share your experience?

Thanks a lot
Bai
