### ISSUE TITLE
MD5 does NOT match - corrupted download

### ISSUE THREAD

**Issue by rjovelin** [EGA-archive/ega-download-client#46] opened 2019-06-26 20:12 UTC
Trying to download bams with the new feature --max-retries -1.
Connection still breaks but this time but I can fully download the file. However, the file is removed because of non-matching md5sums. What is causing the non-matching md5sums? Could it be because the connection aborts? 
I was only able to download 6 files. All other successful downloads (> 30) result in non-matching md5sums. 

 96%|█████████▋| 286G/296G [00:00<00:00, 689GB/s]
[2019-06-22 21:35:45 -0400] ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2019-06-22 21:35:50 -0400] retry attempt 132
[2019-06-22 21:35:50 -0400] Download starting [using 1 connection(s)]...
100%|██████████| 296G/296G [4:32:50<00:00, 18.1MB/s]
[2019-06-23 02:08:40 -0400] Saving...
[2019-06-23 02:24:56 -0400] MD5 does NOT match - corrupted download
[2019-06-23 02:25:01 -0400] retry attempt 133

**Comment by AlexanderVi** [comment] 2019-06-27 08:15
which version do you use?

**Comment by rjovelin** [comment] 2019-06-27 14:55
pyEGA3 - EGA python client version 3.0.33

**Comment by AlexanderVi** [comment] 2019-06-27 15:03
please upgrade to 3.0.38 ( pip3 install pyega3 )

**Comment by rjovelin** [comment] 2019-06-27 15:16
Thanks for the prompt reply. I upgraded to pyega3 3.0.38 and started downloading.

**Comment by rjovelin** [comment] 2019-07-03 15:10
Still impossible to download files with upgraded pyega3. Listing the errors below:
- connection aborted
- slice error
- md5 not matching
- authentification failure


[2019-07-03 04:02:49 -0400] ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2019-07-03 04:02:54 -0400] retry attempt 494
[2019-07-03 04:02:54 -0400] Download starting [using 1 connection(s)]...
 95%|█████████▌| 283G/296G [00:00<00:00, 705GB/s]
[2019-07-03 04:02:54 -0400] ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2019-07-03 04:02:59 -0400] retry attempt 495
[2019-07-03 04:02:59 -0400] Download starting [using 1 connection(s)]...
100%|█████████▉| 295G/296G [5:54:31<312:55:22, 1.01kB/s]
[2019-07-03 09:57:31 -0400] Slice error: received=295298623187, requested=296432615464, file='/scratch2/groups/gsi/bis/EGA_Downloads/EGAD00001002739/CPCG0100-B1_F1.bam-from-0-len-296432615464.slice'
[2019-07-03 09:57:36 -0400] retry attempt 496
[2019-07-03 09:57:39 -0400] Authentication success for user 'richard.jovelin@oicr.on.ca'
[2019-07-03 09:57:39 -0400] Download starting [using 1 connection(s)]...
100%|██████████| 296G/296G [42:16<00:00, 117MB/s]
[2019-07-03 10:39:55 -0400] Saving...
[2019-07-03 11:01:09 -0400] MD5 does NOT match - corrupted download
[2019-07-03 11:01:14 -0400] retry attempt 497
Authentication failure for user 'richard.jovelin@oicr.on.ca'

**Comment by jamiehall007** [comment] 2019-07-12 09:08
I am also experiencing MD5 issues with 3.0.38 - initially reported to EGA and logged as ticket EGADLOAD-120 (multiple log files provided)

I can download dataset **EGAD00000000115** without any issues

All attempts to download dataset **EGAD00010001722** result in "MD5 does NOT match - corrupted download".

**Comment by ilykos** [comment] 2019-07-22 08:25
Same issues here. Files deviate in size by several bits, sometimes more.

**Comment by kkleinoros** [comment] 2019-08-19 20:08
Has this issue been resolved?  Anyone have a fix for this problem?

**Comment by AlexanderVi** [comment] 2019-08-20 07:58
which dataset are you trying to download?  EGAD00010001722 used to have invalid MD5 on the server side ( has been fixed ).

**Comment by kkleinoros** [comment] 2019-08-20 11:48
Thank you for your reply.
I have included a file with the 8 samples I am having difficulty with.  I am using the fetch command with the –c 4 option.
Any other options I should include.
Kathleen

**Comment by AlexanderVi** [comment] 2019-08-20 12:49
which exactly error do you observe ( connection aborted, slice error, md5 not matching or authentification failure ) ? Also which version of pyega do you use?

**Comment by kkleinoros** [comment] 2019-08-20 22:22
I am using version 3.0.38
It alternaates between MD5 does NOT match - corrupted download
and slice error.

**Comment by anandmohan777** [comment] 2019-11-22 17:25
Hi All, We have upgraded our servers so pls update the pyega3 using command 'pip3 install update pyega3 -U' and then try the download. The current version is version 3.0.44.

**Closed by anandmohan777** 2019-11-22 17:25 UTC

**Comment by rdmorin** [comment] 2021-02-06 19:22
We still have this issue with some large data sets we have tried to download (using the current version of pyega3 3.4.1). Is there any known reason for some bams having slice errors or md5 mismatches more often (or consistently)? Is there a chunk number that helps reduce this risk?

**Comment by malloryfreeberg** [comment] 2021-02-10 14:12
Hi @rdmorin . Thanks for raising this and I'm sorry that you're still experiencing this issue with large datasets. Without more information it is hard to diagnose this particular issue, but it sounds like the issue is related to network transfer, which could be on EGA's side or your local network. You could try to increase the number of connections you use to download large files, as each connection downloads an individual chunk, so more connections = more (smaller) chunks. Actual performance will always depend on factors including your local network/infrastructure and the current load on EBI.

To note, there was a brief service disruption at the end of last week, so if you experienced this issue recently I encourage you to try again and see if things are improved. If you require support for your specific downloads, please email the EGA Helpdesk at helpdesk@ega-archive.org and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team will be able to provide further assistance. Thanks for using pyega3!

**Comment by Jungal10** [comment] 2024-06-03 07:20
In 2024, I still have the same error. Every single file comes with md5 errors, Tried with multiple `-c`
