### ISSUE TITLE
cannot fit 'int' into an index-sized integer error

### ISSUE THREAD

**Issue by volkyx** [EGA-archive/ega-download-client#14] opened 2018-07-02 15:15 UTC
I was able to login, however when I try to fetch a file with the following command
"python pyega3/pyega3.py -cf CREDENTIALS_FILE fetch <file_of_interest>"
I got this error
--"Output file:'C:\Users\user\Output file.txt.gz'
File Id: 'File Id'(8404048888 bytes).
Download starting [using 1 connection(s)]...
  0%|                                            | 0.00/7.83G [00:00<?, ?B/s]
cannot fit 'int' into an index-sized integer"--

Please let me know anyone could help me to identify and solve the issue here.

Thanks!

**Comment by AlexanderVi** [comment] 2018-07-03 11:51
Please install the latest version ( currently 3.0.19 )  via pip ( exact command is : sudo pip3 install pyega3 ) and try again : pyega3 -cf CREDENTIALS_FILE fetch <file_of_interest>
PS. Do you runs the client via python 2 or python 3 ? (  Only python 3 is supported )

**Comment by volkyx** [comment] 2018-07-03 14:24
I am running this on a windows environment. I have updated ega-client to 3.0.19 and I started getting this kind of error. 

Traceback (most recent call last):
  File "pyega3/pyega3.py", line 367, in <module>
    main()
  File "pyega3/pyega3.py", line 358, in main
    download_dataset( credentials, args.identifier, args.connections, key, args.
saveto )
  File "pyega3/pyega3.py", line 300, in download_dataset
    reply = api_list_files_in_dataset(token, dataset_id)
  File "pyega3/pyega3.py", line 91, in api_list_files_in_dataset
    if( not dataset in api_list_authorized_datasets(token) ):
  File "pyega3/pyega3.py", line 69, in api_list_authorized_datasets
    r.raise_for_status()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/metadata/datasets

**Comment by AlexanderSenf** [comment] 2018-07-04 14:16
This is an error we can not reproduce in Linux; it appears that the error happens when the file size is larger than the maximum value of a 32-bit integer (which would be about 2.3 GB). Could you please validate that you have the 64-bit environment for Python installed on Windows? (e.g. "Python 3.6 (64-bit))
The HTTPError listed above was due to a temporary issue with the internal load balancing - this request was forwarded to a service that was not running at that time. You should no longer experience this error.

**Comment by volkyx** [comment] 2018-07-05 15:12
Yes it seems it is because of 64 bit incompatibility which I didn't recognize during the python install. Download is working right now. 

Thank you.

**Comment by AlexanderSenf** [comment] 2018-07-05 15:16
Thank you very much. I will close this issue then. Please let us know if there are any further issues.

**Closed by AlexanderSenf** 2018-07-05 15:16 UTC
