### ISSUE TITLE
Cannot download any more - Invalid username, password or secret key

### ISSUE THREAD

**Issue by jakalssj3** [EGA-archive/ega-download-client#193] opened 2023-03-02 09:43 UTC
Since today, I cannot download anything from EGA using the pyega3 client. I keep getting the same error for download attempts or simply when I want to list the available datastes. It worked before (with the issues I raised in another thread). I tested this with two different username/password combinations and with different servers on which I have the client installed.

`[2023-03-02 10:40:41 +0100]
[2023-03-02 10:40:41 +0100] pyEGA3 - EGA python client version 5.0.2 (https://github.com/EGA-archive/ega-download-client)
[2023-03-02 10:40:41 +0100] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2023-03-02 10:40:41 +0100] Python version : 3.8.5
[2023-03-02 10:40:41 +0100] OS version : Linux #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021
[2023-03-02 10:40:41 +0100] Server URL: https://ega.ebi.ac.uk:8443/v2
[2023-03-02 10:40:41 +0100] Session-Id: 550003350
[2023-03-02 10:40:46 +0100]
[2023-03-02 10:40:46 +0100] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
Traceback (most recent call last):
  File "/home/my_user/.local/lib/python3.8/site-packages/pyega3/libs/auth_client.py", line 37, in token
    r.raise_for_status()
  File "/home/my_user/.local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token`

**Comment by Naivenerd** [comment] 2023-03-02 10:44
I had the same problem. Interestingly:

- The previously normal network is also unable to connect.
- I tried various loacations for various VPNS, and all of them failed to connect.
- The same error reported every time.

> [2023-03-02 18:28:52 +0800] Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org
> Traceback (most recent call last):
>   File "c:\app\python37\lib\site-packages\pyega3\libs\auth_client.py", line 37, in token
>     r.raise_for_status()
>   File "c:\app\python37\lib\site-packages\requests\models.py", line 953, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token

**Comment by Naivenerd** [comment] 2023-03-02 11:02
In addition, I got the same error when I run
`pyega3 -d -t datasets`
The test count is invalid? Where did the problem occur?

**Comment by jakalssj3** [comment] 2023-03-02 11:04
> In addition, I got the same error when I run
>pyega3 -d -t datasets
>The test count is invalid? Where did the problem occur?

Same issue here.. But I can still log in to the EGA website and see my datasets.

**Comment by CsabaHalmagyi** [comment] 2023-03-02 11:44
Hello,
Thank you for raising this. We are currently experiencing some issues with one of the production databases responsible for downloading. This has been reported to the DBA team and they are working on a solution already.

**Comment by suhartobanerjee** [comment] 2023-03-02 13:18
Thanks for providing an update and am happy that the team is working on this. I also had the same issue today, was going to mail the helpdesk when I saw this on the issues section. Looking forward to the fix!

**Comment by nzx9581** [comment] 2023-03-03 07:17
Same problem too, and it still cannot validate my username and password.

**Comment by jason2389** [comment] 2023-03-03 09:34
Same problem here!

**Comment by jakalssj3** [comment] 2023-03-03 14:19
It seems to work now finally:

`[2023-03-03 15:18:34 +0100] pyEGA3 - EGA python client version 5.0.2 (https://github.com/EGA-archive/ega-download-client)
[2023-03-03 15:18:34 +0100] Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly
[2023-03-03 15:18:34 +0100] Python version : 3.8.5
[2023-03-03 15:18:34 +0100] OS version : Linux #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021
[2023-03-03 15:18:34 +0100] Server URL: https://ega.ebi.ac.uk:8443/v2
[2023-03-03 15:18:34 +0100] Session-Id: 3513577463
[2023-03-03 15:18:35 +0100]
[2023-03-03 15:18:35 +0100] Authentication success for user 'XXXXXX'`

**Comment by Mousiekin** [comment] 2023-03-04 13:08
I have also been chasing my tail trying to download from EGA the last couple of weeks, but I have just had success with pyega3==4.0.5 as suggested by someone else in a previous post.
Versions 5.0.1 and 5.0.2 md5 sum never added up and downloading just went round and round forever trying to reach the correct sum. I am also a bit curious to why my slice was exactly half the size to requested size, which seems very non-random to me. 
Exception: Slice error: received=52428800, requested=104857600

**Comment by Naivenerd** [comment] 2023-03-05 03:58
> I have also been chasing my tail trying to download from EGA the last couple of weeks, but I have just had success with pyega3==4.0.5 as suggested by someone else in a previous post. Versions 5.0.1 and 5.0.2 md5 sum never added up and downloading just went round and round forever trying to reach the correct sum. I am also a bit curious to why my slice was exactly half the size to requested size, which seems very non-random to me. Exception: Slice error: received=52428800, requested=104857600

Thank you very much for your reminding. I have been suffering `Slice error` for days and got little progressing in downloading. 
I just went back to pyega3==4.0.5 and finally succeed to download large files at last (though I still met several slice error). I do have a bad Internet connection, but it seems that the older version works better in this kind of situation.

**Comment by Naivenerd** [comment] 2023-03-06 12:51
@aaclan-ebi My problem is not md5 checksum. I couldn't even get to MD5 checksum step because of frequent `Slice error` in my  poor Internet condition. I chose pyega3==4.0.5 cuz I found that in the old version I can keep more downloaded slices each time `Slice error` occurred.

**Comment by suhartobanerjee** [comment] 2023-03-06 14:17
I can confirm that I was able to download files using pyega3=4.0.5 as many have mentioned in this thread. I was using 30 connections and the download speed was pretty good too! Thank you to everyone who mentioned about their success with this version. Hoping the the current version will be debugged soon. Thanks for your work devs!

**Comment by Naivenerd** [comment] 2023-03-06 15:09
@aaclan-ebi My speed is not very slow, but my network stability is poor. In my area I have to use VPN while downloading, which causes that sometime the speed could reach 5Mb/s (if I use multiple parallel python environments it could be multiplied) and sometime the connection is down for a while. In the [5.0.*] if unfortunately the connection has been disconnected for too long, there will be a lot of data that I have to download again. Actually, I don't mind the slow Internet speed as long as the files could eventually be downloaded. What bothers me is re-downloading again and again which cause the lack of progress.

**Comment by Mousiekin** [comment] 2023-03-06 15:17
Hi Alegria,
these were the only two I was really trying:
EGAF00001156391
EGAF00001156382
thanks,
Marian

**Comment by CsabaHalmagyi** [comment] 2023-03-09 11:33
Thank you for the update Alegria. Closing the issue.

**Closed by CsabaHalmagyi** 2023-03-09 11:33 UTC
Labels: bug
